Fix exception for superusers when opening `/dashboard`
```
AttributeError

/dashboard/

'NoneType' object has no attribute 'is_amc_admin'
```

This fix is a must for `tahoe-sites` migration and will break for all
users once we migrate off the `edx-organizations` fork,
so it's good that we caught it while it's only broken for superusers.